// Copyright 2025 莫维龙 <kalandramo@gmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/srxstack/gintpl. The professional
// version of this repository is https://github.com/srxstack/srxstack.

// 第三方服务示例

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.1
// source: apiserver/v1/frostmourne.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrostmourneLoginRequest 登录请求
//
//	成功
//	    http://127.0.0.1:8080/api/monitor-api/user/login
//	    {username: "admin", password: "111111"}
//	    {returncode: 0, message: "ok", result: "token_value"}
//	失败
//	    http://127.0.0.1:8080/api/monitor-api/user/login
//	    {username: "admin", password: "111111"}
//	    {returncode: 580, message: "用户名或密码错误"}
type FrostmourneLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password 密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrostmourneLoginRequest) Reset() {
	*x = FrostmourneLoginRequest{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrostmourneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrostmourneLoginRequest) ProtoMessage() {}

func (x *FrostmourneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrostmourneLoginRequest.ProtoReflect.Descriptor instead.
func (*FrostmourneLoginRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{0}
}

func (x *FrostmourneLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FrostmourneLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// FrostmourneLoginResponse 登录响应
type FrostmourneLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// returncode 响应码
	Returncode int32 `protobuf:"varint,1,opt,name=returncode,proto3" json:"returncode,omitempty"`
	// message 消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// result 额外消息
	Result        string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrostmourneLoginResponse) Reset() {
	*x = FrostmourneLoginResponse{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrostmourneLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrostmourneLoginResponse) ProtoMessage() {}

func (x *FrostmourneLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrostmourneLoginResponse.ProtoReflect.Descriptor instead.
func (*FrostmourneLoginResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{1}
}

func (x *FrostmourneLoginResponse) GetReturncode() int32 {
	if x != nil {
		return x.Returncode
	}
	return 0
}

func (x *FrostmourneLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FrostmourneLoginResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// CreateFrostmourneDepRequest 创建部门请求
//
//	成功
//	    http://127.0.0.1:8080/api/monitor-api/department/create?_appId=frostmourne&_t=1744881469677
//	    {departmentName: "INFRA", fullName: "infrastructure"}
//	    {"returncode":0,"message":"ok","result":true}
//	失败
//	    http://127.0.0.1:8080/api/monitor-api/department/create?_appId=frostmourne&_t=1744881469677
//	    {departmentName: "INFRA", fullName: "infrastructure"}
//	    {"returncode":5101,"message":"部门已经存在"}
type CreateFrostmourneDepRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// departmentName 部门名称
	DepartmentName string `protobuf:"bytes,1,opt,name=departmentName,proto3" json:"departmentName,omitempty"`
	// fullName 部门全称
	FullName      string `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrostmourneDepRequest) Reset() {
	*x = CreateFrostmourneDepRequest{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrostmourneDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrostmourneDepRequest) ProtoMessage() {}

func (x *CreateFrostmourneDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrostmourneDepRequest.ProtoReflect.Descriptor instead.
func (*CreateFrostmourneDepRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFrostmourneDepRequest) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *CreateFrostmourneDepRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// CreateFrostmourneTeamRequest 创建团队请求
//
//	成功
//	    http://127.0.0.1:8080/api/monitor-api/team/create?_appId=frostmourne&_t=1744884889951
//	    {departmentId: 6, teamName: "INFRA", fullName: "infrastructure"}
//	    {returncode: 0, message: "ok", result: true}
//	失败
//	    http://127.0.0.1:8080/api/monitor-api/team/create?_appId=frostmourne&_t=1744884889951
//	    {departmentId: 6, teamName: "INFRA", fullName: "infrastructure"}
//	    {returncode: 567, message: "团队名已经存在"}
type CreateFrostmourneTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// departmentId 部门ID
	DepartmentId int32 `protobuf:"varint,1,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	// teamName 团队ID
	TeamName string `protobuf:"bytes,2,opt,name=teamName,proto3" json:"teamName,omitempty"`
	// fullName 团队名称
	FullName      string `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrostmourneTeamRequest) Reset() {
	*x = CreateFrostmourneTeamRequest{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrostmourneTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrostmourneTeamRequest) ProtoMessage() {}

func (x *CreateFrostmourneTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrostmourneTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateFrostmourneTeamRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFrostmourneTeamRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *CreateFrostmourneTeamRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *CreateFrostmourneTeamRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// CreateFrostmourneUserRequest 创建用户请求
//
//	成功
//	    http://127.0.0.1:8080/api/monitor-api/userinfo/create?_appId=frostmourne&_t=1744786084135
//	    {role: "user", teamId: 3, account: "test", password: "123456789", fullName: "测试", roles: ["user"]}
//	    {returncode: 0, message: "ok", result: true}
//
//	失败
//	    http://127.0.0.1:8080/api/monitor-api/userinfo/create?_appId=frostmourne&_t=1744786206214
//	    {role: "user", teamId: 3, account: "test", password: "123456789", fullName: "测试", roles: ["user"]}
//	    {returncode: 5690, message: "账号已经存在"}
type CreateFrostmourneUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role 用户所属角色
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// teamId 团队ID
	TeamId int32 `protobuf:"varint,2,opt,name=teamId,proto3" json:"teamId,omitempty"`
	// account 账号
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// password 密码
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// fullName 全称
	FullName string `protobuf:"bytes,5,opt,name=fullName,proto3" json:"fullName,omitempty"`
	// roles 所属角色列表
	Roles         []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrostmourneUserRequest) Reset() {
	*x = CreateFrostmourneUserRequest{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrostmourneUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrostmourneUserRequest) ProtoMessage() {}

func (x *CreateFrostmourneUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrostmourneUserRequest.ProtoReflect.Descriptor instead.
func (*CreateFrostmourneUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFrostmourneUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateFrostmourneUserRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreateFrostmourneUserRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateFrostmourneUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateFrostmourneUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateFrostmourneUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// CommonFrostmourneResponse 公共响应信息
type CommonFrostmourneResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// returncode 响应码
	Returncode int32 `protobuf:"varint,1,opt,name=returncode,proto3" json:"returncode,omitempty"`
	// message 消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// result 结果 true or false
	Result        bool `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonFrostmourneResponse) Reset() {
	*x = CommonFrostmourneResponse{}
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonFrostmourneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonFrostmourneResponse) ProtoMessage() {}

func (x *CommonFrostmourneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_frostmourne_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonFrostmourneResponse.ProtoReflect.Descriptor instead.
func (*CommonFrostmourneResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_frostmourne_proto_rawDescGZIP(), []int{5}
}

func (x *CommonFrostmourneResponse) GetReturncode() int32 {
	if x != nil {
		return x.Returncode
	}
	return 0
}

func (x *CommonFrostmourneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonFrostmourneResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_apiserver_v1_frostmourne_proto protoreflect.FileDescriptor

var file_apiserver_v1_frostmourne_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x31, 0x22, 0x51, 0x0a, 0x17, 0x46, 0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75,
	0x72, 0x6e, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6c, 0x0a, 0x18, 0x46, 0x72, 0x6f, 0x73, 0x74,
	0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x61, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7a, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x6d, 0x0a, 0x19, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x73, 0x74, 0x6d, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x78, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f,
	0x67, 0x69, 0x6e, 0x74, 0x70, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiserver_v1_frostmourne_proto_rawDescOnce sync.Once
	file_apiserver_v1_frostmourne_proto_rawDescData = file_apiserver_v1_frostmourne_proto_rawDesc
)

func file_apiserver_v1_frostmourne_proto_rawDescGZIP() []byte {
	file_apiserver_v1_frostmourne_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_frostmourne_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiserver_v1_frostmourne_proto_rawDescData)
	})
	return file_apiserver_v1_frostmourne_proto_rawDescData
}

var file_apiserver_v1_frostmourne_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apiserver_v1_frostmourne_proto_goTypes = []any{
	(*FrostmourneLoginRequest)(nil),      // 0: v1.FrostmourneLoginRequest
	(*FrostmourneLoginResponse)(nil),     // 1: v1.FrostmourneLoginResponse
	(*CreateFrostmourneDepRequest)(nil),  // 2: v1.CreateFrostmourneDepRequest
	(*CreateFrostmourneTeamRequest)(nil), // 3: v1.CreateFrostmourneTeamRequest
	(*CreateFrostmourneUserRequest)(nil), // 4: v1.CreateFrostmourneUserRequest
	(*CommonFrostmourneResponse)(nil),    // 5: v1.CommonFrostmourneResponse
}
var file_apiserver_v1_frostmourne_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_frostmourne_proto_init() }
func file_apiserver_v1_frostmourne_proto_init() {
	if File_apiserver_v1_frostmourne_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiserver_v1_frostmourne_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_frostmourne_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_frostmourne_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_frostmourne_proto_msgTypes,
	}.Build()
	File_apiserver_v1_frostmourne_proto = out.File
	file_apiserver_v1_frostmourne_proto_rawDesc = nil
	file_apiserver_v1_frostmourne_proto_goTypes = nil
	file_apiserver_v1_frostmourne_proto_depIdxs = nil
}
