// 第三方服务示例

// Copyright 2025 莫维龙 <kalandramo@gmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/srxstack/gintpl. The professional
// version of this repository is https://github.com/srxstack/srxstack.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *FrostmourneLoginRequest) Default() {
}

func (x *FrostmourneLoginResponse) Default() {
}

func (x *CreateFrostmourneDepRequest) Default() {
}

func (x *CreateFrostmourneTeamRequest) Default() {
}

func (x *CreateFrostmourneUserRequest) Default() {
}

func (x *CommonFrostmourneResponse) Default() {
}
